# docker-compose-template.yml
version: '3.8'

services:
  frontend:
    image: ramanapatel/frontend:41
    ports:
      - "80:80"
    restart: unless-stopped

  backend:
    image: ramanapatel/backend:41
    ports:
      - "8000:8000"
    restart: unless-stopped

